# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            AI for Security
tagline:          'A Security blog'
description:      'With all the fears and hopes of what AI can bring to cyber security, let us take a deep dive into the possibilities'
url:              http://
baseurl:          /

author:
  name:           'Pasquale Kress'
  url:            https://

# paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://
